---
- hosts: vpn
  remote_user: debian
  vars:
    port: 443
    protocol: tcp
    ovpnNumber: "{{ hostvars[inventory_hostname].fournisseur }}"

  tasks:
  - name: Check if the setup script exists
    stat:
      path: /home/vpn/setup_from_naboo_ansible.sh
    register: vpn_installed

  - name: Kill OpenVPN
    become: true
    become_method: sudo
    command: pkill openvpn

  - name: Uninstall script is built
    become: true
    become_method: sudo
    template: src=templates/oneliner_uninstall.j2 dest=/home/uninstall_vpn_ansible.sh
      owner=debian
      mode=0777
    when: vpn_installed.stat.exists == true

  - name: Launch of the uninstalling script
    become: true
    become_method: sudo
    command: bash /home/uninstall_vpn_ansible.sh
    when: vpn_installed.stat.exists == true

  - name: Uninstall script is deleted
    become: true
    become_method: sudo
    file:
      path: /home/uninstall_vpn_ansible.sh
      state: absent
    when: vpn_installed.stat.exists == true

  - name: Remove VPN directory
    become: true
    become_method: sudo
    file:
      path: /home/vpn/
      recurse: true
      state: directory
    when: vpn_installed.stat.exists == true

#  - name: Remove VPN tunnels
#    command: "ip link delete tun0"
#    delegate_to: localhost
