---


#FIXME: Le script tunnel.sh ne focntionne pas car le path du .ovpn est hardcodé dedans


# On vérifie si aucun tag n'a été défini, dans ce cas on affiche une invite pour choisir l'action a effectuer.
# Le résultat de l'user input est stocké dans hostvars.localhost.pause_result.user_input. Il vaut un string ("1", "2", etc...) si aucun tag a été défini, ou est undefined si au moins un tag a été précisé. Cette variable est TREES CHIANTE à récupérer puisqu'elle ests sur l'host 'localhost'

# On a: hostvars.localhost.pause_result.user_input qui contient la réponse (ou qui est undefined si les tags sont utilisés)

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check args
      pause: 
        prompt: "WARNING: It looks like you didn't used any tag.\n
        You can use the argument '--tags tag1,tag2,...' to sepcify one or more action to run\n
        What do you want to do now?\n\n
        [1]: Install OpenVPN (and configure it) (--tags install)\n
        [2]: Remove OpenVPN (--tags uninstall)\n
        [3]: Uninstall and reinstall OpenVPN (--tags install,uninstall)\n
        [4]: Stop OpenVPN (--tags stop)\n
        [5]: Start the tunnels and FireqOS (--tags start)\n
        [6]: Just change current config (--tags reconf)"
      register: pause_result
      

    

# Et maintenant on s'occupe vraiment des VPNs
- hosts: vpn
  remote_user: debian
  vars:
    subnet: "{{ hostvars[inventory_hostname].subnet }}"
    port: 5010
    protocol: tcp
    ovpnNumber: "{{ hostvars[inventory_hostname].fournisseur }}"
    packages: ['openvpn', 'iptables', 'openssl', 'htop', 'tmux', 'screen', 'neovim', 'hexedit', 'vim', 'emacs', 'fireqos', 'iftop', 'bmon', 'curl', 'ca-certificates', 'iperf3']
    # OPENVPN
    default_args: --route-noexec --daemon
    extra_args: 
  tasks:  # ****************************** UNINSTALL *************************************
      
    - name: === STOP ===
      block:
      - name: Kill OpenVPN on remote
        become: true
        become_method: sudo
        command: pkill openvpn
        ignore_errors: true
      
      - name: Kill OpenVPN on localhost # FIXME : Figure out whether you can only kill for one tunnel
        become: true
        become_method: sudo
        command: pkill -f "openvpn --config ../openvpn_files/client-{{ ovpnNumber }}.ovpn" 
        delegate_to: localhost
        ignore_errors: true
      
      - name: Stop FireQOS on remote
        become: true
        become_method: sudo
        command: fireqos stop
        
      when: (hostvars.localhost.pause_result is defined and (hostvars.localhost.pause_result.user_input == "2" or hostvars.localhost.pause_result.user_input == "3" or hostvars.localhost.pause_result.user_input == "4" or hostvars.localhost.pause_result.user_input == "6") ) or hostvars.localhost.pause_result is not defined
      tags: [ uninstall, stop, reconf ]
      
    - name: === Uninstall ===
      block:
      - name: Remove Additional Tools Config (FireQOS)
        become: true
        become_method: sudo
        file:
          state: absent
          path: /etc/firehol/fireqos.conf

      - name: Remove IP Table rule for NAT
        become: true
        become_method: sudo
        command: iptables -t nat -D POSTROUTING -o en+ -j MASQUERADE
        ignore_errors: true

        #- name: Uninstall additional tools
        #become: true
        #become_method: sudo
        #apt:
        #        state: absent
        #        purge: true
        #        name: "{{ packages }}"
        #
        # As it turns out, none of the tools we have really need to be
        # removed that badly. We can let them sit there until the VPS
        # expires. Also, this part is dangerous to use in testing on
        # machines where these other packages are dependencies of
        # working services, which configuration will get wiped.
        # Source : the apache2 server I accidentally wiped clean from my VPS
                
      # Uninstall script begins here
      - name: Uninstall and purge OpenVPN
        become: true
        become_method: sudo
        apt:
                name: openvpn
                purge: True
                state: absent

      - name: Remove OVPN config files and VPN directory
        become: true
        become_method: sudo
        file:
                state: absent
                path: "{{ item }}"
        loop:
            - /etc/openvpn
            - /etc/sysctl.d/30-openvpn-forward.conf
            - /home/vpn
            - /home/client-{{ ovpnNumber }}

      when: (hostvars.localhost.pause_result is defined and (hostvars.localhost.pause_result.user_input == "2" or hostvars.localhost.pause_result.user_input == "3")) or hostvars.localhost.pause_result is not defined
      tags: [ uninstall ]
      
      
    # ************************ INSTALL *****************************************
    - name: Install packages and utilities
      become: true
      become_method: sudo
      apt:
        name: "{{ packages }}"
        state: present
        install_recommends: false # DO NOT LET IT INSTALL FIREHOL, DO NOT. (cf. Readme)
        update_cache: yes
      when: (hostvars.localhost.pause_result is defined and (hostvars.localhost.pause_result.user_input == "1" or hostvars.localhost.pause_result.user_input == "3" )) or hostvars.localhost.pause_result is not defined
      tags: [ install ]
        
    - name: === Install ===
      block:
        - name: Create a folder for the VPN software
          become: true
          become_method: sudo
          file:
            path: /home/vpn
            state: directory

        - name: Copy the key generation script
          become: true
          become_method: sudo
          template: src=templates/certgen.sh.j2 dest=/home/vpn/certgen.sh
          
        - name: Copy the server.conf to the remote server
          become: true
          become_method: sudo
          template: src=templates/server.conf.j2 dest=/etc/openvpn/server.conf
            #owner=root
            #mode=0777
            
        - name: Copy the client.ovpn file to the server to apply the template
          become: true
          become_method: sudo
          template:
            src: templates/client.conf.j2
            dest: "/home/vpn/client-{{ ovpnNumber }}.ovpn"

        - name: Copy FireQoS config
          become: true
          become_method: sudo
          template:
            src: templates/fireqos_vpn.conf
            dest: /etc/firehol/fireqos.conf

        - name: Generate the keys
          become: true
          become_method: sudo
          command: bash /home/vpn/certgen.sh
          
        - name: Send dh.pem
          become: true
          become_method: sudo
          template:
            src: templates/dh.pem
            dest: "/etc/openvpn/dh.pem"

        - name: Rename dev tun
          become: true
          become_method: sudo
          lineinfile:            
            path: "/home/vpn/client-{{ ovpnNumber }}.ovpn"
            regexp: '^dev tun'
            line: "dev tun{{groups['vpn'].index(inventory_hostname) + 1}}"

        - name: Repatriate .ovpn files
          become: true
          become_method: sudo
          fetch:
            src: "/home/vpn/client-{{ ovpnNumber }}.ovpn"
            dest: ../openvpn_files/
            flat: true

        - name: Enable IP Forward
          become: true
          become_method: sudo
          shell: echo 1 > /proc/sys/net/ipv4/ip_forward

        - name: IP Table Rule
          become: true
          become_method: sudo
          command: iptables -t nat -A POSTROUTING -o en+ -j MASQUERADE

      when: (hostvars.localhost.pause_result is defined and (hostvars.localhost.pause_result.user_input == "1" or hostvars.localhost.pause_result.user_input == "3" or hostvars.localhost.pause_result.user_input == "6")) or hostvars.localhost.pause_result is not defined
      tags: [ install, reconf ]
      
    # ****************** MOUNT **********************
    - name: === Mounting ===
      block:
        - name: Start openvpn on the remote server
          become: true
          become_method: sudo
          command:
            cmd: "/usr/sbin/openvpn --config /etc/openvpn/server.conf --daemon"
            chdir: /etc/openvpn
          #command: systemctl restart openvpn
          #@server.service)
            
        - name: Deploy tunnels on the local host
          become: true
          become_method: sudo
          command: "/usr/sbin/openvpn --config ../openvpn_files/client-{{ ovpnNumber }}.ovpn {{ default_args }} {{ extra_args}}"
          # WARNING :   If you modify the beginning of this line (between openvpn and .ovpn), remember to modify the openvpn pkill
          #             line for local host up above
          delegate_to: localhost
          
        - name: Start FireQOS
          become: true
          become_method: sudo
          command: "fireqos start"
          
      when: (hostvars.localhost.pause_result is defined and (hostvars.localhost.pause_result.user_input == "1" or hostvars.localhost.pause_result.user_input == "3" or hostvars.localhost.pause_result.user_input == "5" or hostvars.localhost.pause_result.user_input == "6")) or hostvars.localhost.pause_result is not defined
      tags: [ install, start, reconf]
        


